# Generated by Django 2.2.1 on 2020-04-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galerie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=1500, null=True)),
                ('photo', models.ImageField(upload_to='Media')),
                ('slug', models.SlugField()),
            ],
        ),
    ]
