# Generated by Django 2.2.1 on 2020-04-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galerie',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
