# Generated by Django 2.2.1 on 2020-04-10 09:19

from django.db import migrations, models
import galerie.models


class Migration(migrations.Migration):

    dependencies = [
        ('galerie', '0002_auto_20200409_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galerie',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=galerie.models.upload_image_path),
        ),
    ]
