# Generated by Django 2.2.1 on 2019-12-26 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afrik_app', '0002_commentaire_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaire',
            old_name='phone',
            new_name='num',
        ),
    ]
