# Generated by Django 2.2.1 on 2019-12-26 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afrik_app', '0004_auto_20191226_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaire',
            old_name='name',
            new_name='Nom',
        ),
    ]
