# Generated by Django 2.2.1 on 2019-12-26 12:07

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('afrik_app', '0005_auto_20191226_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaire',
            name='num',
        ),
        migrations.AddField(
            model_name='commentaire',
            name='Téléphone',
            field=phone_field.models.PhoneField(blank=True, help_text='Numero de Téléphone', max_length=31),
        ),
    ]
